sudo: required

services:
    - docker

before_install:
- docker build -t im .

script:
- docker run --rm im -help
- docker run --rm -v $(pwd):/imgs im -resize 500 /imgs/test.jpg /imgs/test-resize.jpg